name: rive_common
version: 0.2.8
homepage: https://rive.app
description: Share Rive functionality between the editor and the Flutter runtime.
repository: https://github.com/rive-app/rive-flutter
environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=2.5.0"
dependencies:
  collection: ^1.15.0
  ffi: ^2.0.1
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  graphs: ^2.0.0
  http: ">=0.13.3 <2.0.0"
  meta: ^1.3.0
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  plugin:
    platforms:
      android:
        package: app.rive.rive
        pluginClass: RivePlugin
      macos:
        pluginClass: RivePlugin
      windows:
        pluginClass: RivePlugin
      ios:
        pluginClass: RivePlugin
      web:
        pluginClass: RivePlugin
        fileName: rive_web.dart
